# @package _global_

data:
  dataset: cifar-10

# Good defaults that worked well with resnet18/cifar10
sampling:
  num_groups: 10
  weight:
    contr: 1e1
    cls: 1e3
    tv: 1e5
  noise: 1e-1
  noise_decay_magnitude: 4
  num_steps: 256
  batch_size: 500
  num_batches: 500
